# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tktmb6lnOG6W5LLwSgCFf0ZKnju0Sw1V
"""


import gradio as gr
import reportlab

import math
import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# ==============================================================================
# 1. UNIVERSAL GEOSHIELD PDF REPORT GENERATOR
# ==============================================================================
def generate_pdf_report(title, mode_name, status_text, recs_text, inputs_dict):
    filename = f"GeoShield_{mode_name.replace(' ', '_')}_Report.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Custom Header Styles
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1A365D'),
        spaceAfter=6
    )
    sub_header_style = ParagraphStyle(
        'SubHeaderStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=15
    )

    # Title & Subtitle
    story.append(Paragraph("<b>GeoShield: Geological Hazard & Slope Safety Report</b>", header_style))
    story.append(Paragraph(f"<b>Assessment Level:</b> {title} | <b>Generated Mode:</b> {mode_name}", sub_header_style))
    story.append(Spacer(1, 10))

    # Hazard Status Banner
    status_style = ParagraphStyle('StatusStyle', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#2B6CB0'))
    story.append(Paragraph(f"<b>Assessment Result:</b> {status_text}", status_style))
    story.append(Spacer(1, 12))

    # Inputs Table
    story.append(Paragraph("<b>Field Parameters & Calculations Summary:</b>", styles['Heading3']))
    table_data = [["Parameter", "Input Value / Evaluated Metric"]]
    for key, value in inputs_dict.items():
        table_data.append([str(key), str(value)])

    param_table = Table(table_data, colWidths=[220, 250])
    param_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2B6CB0')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E0')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(param_table)
    story.append(Spacer(1, 15))

    # Engineering Mitigation Measures
    story.append(Paragraph("<b>Actionable Recommendations & Mitigation Plan:</b>", styles['Heading3']))
    formatted_recs = recs_text.replace('\n', '<br/>')
    story.append(Paragraph(formatted_recs, styles['Normal']))

    doc.build(story)
    return filename

# ==============================================================================
# 2. TIER-1: RAPID FIELD SCREENING LOGIC (NON-TECHNICAL)
# ==============================================================================
def tier1_rapid_screening(slope_type, veg_cover, visual_cracks, water_seepage, rain_condition):
    score = 0

    # 1. Slope Category
    if slope_type == "Flat / Gentle Slope (<15°)": score += 5
    elif slope_type == "Moderate Slope (15°-35°)": score += 20
    elif slope_type == "Steep Slope / Cliff (>35°)": score += 35

    # 2. Vegetation
    if veg_cover == "Dense Trees / Vegetation": score -= 10
    elif veg_cover == "Sparse Grass / Shrubs": score += 10
    elif veg_cover == "Bare Soil / Barren Rock": score += 20

    # 3. Visual Signs
    if visual_cracks == "Yes": score += 25
    if water_seepage == "Yes": score += 15

    # 4. Triggering Factor (Rainfall)
    if rain_condition == "Heavy / Continuous Rain": score += 25
    elif rain_condition == "Moderate Rain": score += 15

    score = max(0, min(100, score))

    inputs_dict = {
        "Slope Geometry": slope_type,
        "Vegetation Cover": veg_cover,
        "Visible Ground Cracks": visual_cracks,
        "Water Seepage / Wetness": water_seepage,
        "Rainfall Condition": rain_condition,
        "Landslide Risk Score": f"{score} / 100"
    }

    if score < 35:
        status = f"🟢 Low Hazard Risk (Score: {score}/100)"
        recs = (
            "• Site is currently STABLE under observation.\n"
            "• Keep surface drainage channels clear of debris.\n"
            "• Avoid deforestation or cutting vegetation along slope toe."
        )
    elif score < 65:
        status = f"🟡 Moderate Hazard Risk (Score: {score}/100)"
        recs = (
            "• CAUTION: Slope is vulnerable during active precipitation.\n"
            "• Monitor tension cracks and water seepage points daily.\n"
            "• Clear drainage outlets to avoid water accumulation behind slope.\n"
            "• Prepare field evacuation protocol if rain persists."
        )
    else:
        status = f"🔴 High Hazard Risk (Score: {score}/100)"
        recs = (
            "⚠️ HIGH DANGER / IMMINENT FAILURE HAZARD!\n"
            "• Immediately evacuate toe and crest zones.\n"
            "• Restrict traffic and infrastructure access near slope.\n"
            "• Notify local disaster management & response authorities instantly."
        )

    pdf_path = generate_pdf_report("Tier-1 Rapid Screening", "Field_Screening", status, recs, inputs_dict)
    return status, recs, pdf_path

# ==============================================================================
# 3. TIER-2: ADVANCED GEOTECHNICAL ANALYSIS LOGIC (ENGINEERS)
# ==============================================================================
def tier2_geotechnical_analysis(mat_type, H, beta_deg, surcharge, c, phi_deg, gamma, ru, rmr, joint_orientation):
    inputs_dict = {
        "Material Classification": mat_type,
        "Slope Height (H)": f"{H} m",
        "Slope Angle (β)": f"{beta_deg}°",
        "Surcharge Load (q)": f"{surcharge} kPa"
    }

    if mat_type == "Soil Slope":
        try:
            beta = math.radians(beta_deg)
            phi = math.radians(phi_deg)

            # Limit Equilibrium Planar Failure Equation with Surcharge Load (q) & Slope Height (H)
            W = 0.5 * gamma * (H**2) / math.tan(beta)  # Mass Weight Approximation
            N = (W + surcharge) * math.cos(beta)       # Normal Force
            T = (W + surcharge) * math.sin(beta)       # Driving Shear Force

            pore_pressure = ru * gamma * H
            effective_N = max(0, N - pore_pressure)

            resisting_force = (c * (H / math.sin(beta))) + (effective_N * math.tan(phi))
            driving_force = T

            FS = round(resisting_force / driving_force, 3) if driving_force > 0 else 0.0

            inputs_dict.update({
                "Cohesion (c')": f"{c} kPa",
                "Internal Friction Angle (ϕ')": f"{phi_deg}°",
                "Soil Unit Weight (γ)": f"{gamma} kN/m³",
                "Pore Water Pressure Ratio (ru)": ru,
                "Factor of Safety (FS)": FS
            })

            if FS > 1.5:
                status = f"🟢 Stable Soil Slope (Factor of Safety, FS = {FS})"
                recs = (
                    "• Slope is geotechnically STABLE under current static loads.\n"
                    "• Maintain current drainage system and routine inspections."
                )
            elif 1.0 <= FS <= 1.5:
                status = f"🟡 Marginally Stable Soil Slope (Factor of Safety, FS = {FS})"
                recs = (
                    "• MARGINALLY STABLE: Susceptible to failure during heavy rain/seismic events.\n"
                    "• Engineering Action 1: Install sub-surface horizontal drain pipes.\n"
                    "• Engineering Action 2: Apply bio-engineering solutions (e.g., Vetiver grass planting).\n"
                    "• Avoid adding further surcharge or building structures near crest."
                )
            else:
                status = f"🔴 Critical / Unstable Soil Slope (Factor of Safety, FS = {FS})"
                recs = (
                    "⚠️ CRITICAL STABILITY FAILURE (FS < 1.0)!\n"
                    "• Engineering Intervention 1: Construct retaining structures (Gabion walls / MSE walls).\n"
                    "• Engineering Intervention 2: Install structural soil nails or tie-back anchor bolts.\n"
                    "• Immediate shotcrete sealant application to prevent water infiltration."
                )

        except Exception as err:
            return "Calculation Error", str(err), None

    else:
        # Rock Slope Stability (RMR Adjustment for Discontinuity Dip Orientation)
        joint_penalty = -25 if joint_orientation == "Adverse (Dipping Out of Slope)" else (-5 if joint_orientation == "Fair / Random" else 0)
        adjusted_rmr = rmr + joint_penalty

        inputs_dict.update({
            "Basic RMR Score": rmr,
            "Discontinuity / Joint Condition": joint_orientation,
            "Adjusted Rock Mass Rating": adjusted_rmr
        })

        if adjusted_rmr > 60:
            status = f"🟢 Good Rock Mass - Class I/II (Adjusted RMR = {adjusted_rmr})"
            recs = (
                "• Rock mass is structurally STABLE.\n"
                "• Install spot rock bolting for isolated loose blocks."
            )
        elif 40 <= adjusted_rmr <= 60:
            status = f"🟡 Fair Rock Mass - Class III (Adjusted RMR = {adjusted_rmr})"
            recs = (
                "• MODERATE RISK: Potential Planar/Wedge failure along joint sets.\n"
                "• Engineering Action 1: Install systematic pattern rock bolts.\n"
                "• Engineering Action 2: Apply shotcrete reinforced with wire mesh mesh."
            )
        else:
            status = f"🔴 Poor Rock Mass - Class IV/V (Adjusted RMR = {adjusted_rmr})"
            recs = (
                "⚠️ HIGH ROCKFALL / TOPPLING FAILURE RISK!\n"
                "• Engineering Action 1: Install heavy cable anchors and catch fencing.\n"
                "• Engineering Action 2: Drill horizontal weep holes to relieve groundwater head.\n"
                "• Apply heavy wire netting along cliff face."
            )

    pdf_path = generate_pdf_report("Tier-2 Geotechnical Analysis", "Geotechnical_Analysis", status, recs, inputs_dict)
    return status, recs, pdf_path

# ==============================================================================
# 4. GRADIO INTERFACE LAYOUT (GEOSHIELD DASHBOARD)
# ==============================================================================
with gr.Blocks(title="GeoShield Hazard Dashboard") as demo:
    gr.Markdown(
        """
        # 🛡️ GeoShield: Landslide Risk & Slope Safety Dashboard
        *An automated geological hazard screening and slope stability evaluation tool.*
        """
    )

    with gr.Tabs():
        # TAB 1: TIER-1 RAPID FIELD SCREENING
        with gr.TabItem("🧑‍🌾 Tier-1: Rapid Field Screening (Non-Technical / Public)"):
            gr.Markdown("### Rapid Observation-Based Hazard Index")
            with gr.Row():
                slope_b = gr.Dropdown(
                    ["Flat / Gentle Slope (<15°)", "Moderate Slope (15°-35°)", "Steep Slope / Cliff (>35°)"],
                    label="1. Slope Geometry", value="Moderate Slope (15°-35°)"
                )
                veg_b = gr.Dropdown(
                    ["Dense Trees / Vegetation", "Sparse Grass / Shrubs", "Bare Soil / Barren Rock"],
                    label="2. Vegetation Cover", value="Sparse Grass / Shrubs"
                )
            with gr.Row():
                cracks_b = gr.Radio(["No", "Yes"], label="3. Visible Ground Cracks?", value="No")
                seepage_b = gr.Radio(["No", "Yes"], label="4. Active Water Seepage?", value="No")

            rain_b = gr.Radio(
                ["No / Light Rain", "Moderate Rain", "Heavy / Continuous Rain"],
                label="5. Rainfall Condition", value="Moderate Rain"
            )

            btn_t1 = gr.Button("Evaluate Tier-1 Risk & Generate PDF Report", variant="primary")
            out_t1_status = gr.Textbox(label="Hazard Status")
            out_t1_recs = gr.Textbox(label="Field Safety Instructions", lines=3)
            out_t1_pdf = gr.File(label="Download Tier-1 Field Screening PDF Report")

            btn_t1.click(
                fn=tier1_rapid_screening,
                inputs=[slope_b, veg_b, cracks_b, seepage_b, rain_b],
                outputs=[out_t1_status, out_t1_recs, out_t1_pdf]
            )

        # TAB 2: TIER-2 ADVANCED GEOTECHNICAL ANALYSIS
        with gr.TabItem("👷 Tier-2: Advanced Geotechnical Analysis (Engineers)"):
            gr.Markdown("### Material-Specific Quantitative Slope Stability")
            mat_type = gr.Radio(["Soil Slope", "Rock Slope"], label="1. Material Type", value="Soil Slope")

            with gr.Row():
                H = gr.Number(label="Slope Height, H (m)", value=12.0)
                beta_deg = gr.Number(label="Slope Angle, β (degrees)", value=32.0)
                surcharge = gr.Number(label="Building / Road Surcharge, q (kPa)", value=10.0)

            gr.Markdown("#### 🔹 Soil Parameters (Active for Soil Slopes)")
            with gr.Row():
                c = gr.Number(label="Cohesion, c' (kPa)", value=15.0)
                phi_deg = gr.Number(label="Friction Angle, ϕ' (degrees)", value=28.0)
                gamma = gr.Number(label="Unit Weight, γ (kN/m³)", value=19.0)
                ru = gr.Slider(0.0, 0.5, value=0.2, step=0.05, label="Pore Water Pressure Ratio, ru")

            gr.Markdown("#### 🔸 Rock Mass Parameters (Active for Rock Slopes)")
            with gr.Row():
                rmr = gr.Slider(0, 100, value=50, step=1, label="Basic Rock Mass Rating (RMR)")
                joint_orientation = gr.Dropdown(
                    ["Favorable (Dipping Into Slope)", "Fair / Random", "Adverse (Dipping Out of Slope)"],
                    label="Discontinuity / Joint Dip Orientation", value="Fair / Random"
                )

            btn_t2 = gr.Button("Calculate Geotechnical Stability & Generate PDF Report", variant="primary")
            out_t2_status = gr.Textbox(label="Stability Analysis Result (FS / RMR Class)")
            out_t2_recs = gr.Textbox(label="Engineering Mitigation Measures", lines=4)
            out_t2_pdf = gr.File(label="Download Tier-2 Technical PDF Report")

            btn_t2.click(
                fn=tier2_geotechnical_analysis,
                inputs=[mat_type, H, beta_deg, surcharge, c, phi_deg, gamma, ru, rmr, joint_orientation],
                outputs=[out_t2_status, out_t2_recs, out_t2_pdf]
            )

# Launch App
demo.launch(share=True, debug=True)

